"""Make leaving_timestamp and parking_timestamp and parking_cost nullable

Revision ID: d5e027ac6c2b
Revises: 
Create Date: 2025-07-29 00:00:21.449735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e027ac6c2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.alter_column('parking_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('leaving_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('parking_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('vehicle_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.alter_column('vehicle_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('parking_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('leaving_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('parking_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
